### ISSUE TITLE
Data for Section 4.2.3

### ISSUE THREAD

**Issue by apolaris** [datang1992/Correlated-VAEs#2]
Hello, I notice that the code for CVAEs in this repository is for Section 4.2.3 while the data processing code is for Section 4.2.2. Would you mind release your dataset for Section 4.2.3?

**Comment by datang1992** [comment]
Hi @apolaris Beichen, I have added the preprocessing code for the experiment in Section 4.2.3 and wrote a brief instruction for using it in the README file. Please let me know if you have further questions. Thanks.

Notice that since we are doing random train/test splits on this experiment, the resulting metrics can be slightly different for various splits, but they should not be varying too much.

**Comment by apolaris** [comment]
Thank U！
