### ISSUE TITLE
I has got some questions about the training ratio

### ISSUE THREAD

**Issue by xingyuezhiji** [datang1992/Correlated-VAEs#4]
hello,i try to run 'process_Epinions_data.py' with difference ratio from 0.4 to 0.9,and i found that the less training ration had got the better NCRR. i am confused about that,how to explain it?

**Comment by datang1992** [comment]
We did not test too many different choices for the ratios. Just tried some choices and they are already much better than the baselines. It is possible since it is possible for the link prediction to be a little overfitting. But anyway, our main goal is to show that the proposed CVAE method is better than the baseline methods (which do not involve a ratio value). We did not aim to find the best cross validation results.

**Comment by datang1992** [comment]
Sorry I misunderstood your question in my previous reply and I deleted it. It is possible since for the NCRR since that different training ratio may mean the training/testing split to be very different. We are splitting the edge set on a very sparse graph, so different training ratio may have a very different sparsity on the resulting testing graphs. It is because the testing graphs may vary a lot, not due to the size of the training graphs. Anyway, if you want to compare some algorithms' performance on this code, please use a same ratio for all experiments for fair comparison.

**Comment by xingyuezhiji** [comment]
> so different training ratio may have a very different spars

okay! thanks a lot!

**Comment by datang1992** [comment]
No problem!
